sudo: true
language: cpp
compiler: gcc

install: 
  - sudo apt update -qq
  # Boost
  - sudo apt install -qq libboost-all-dev
  # SDL
  - sudo apt-get install -qq libsdl-dev libsdl-ttf2.0-dev libsdl-image1.2-dev
  # Codecov
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-5 90
  - sudo pip install codecov
  # OCLint
  - ./install_oclint


# Start virtual X server, from https://docs.travis-ci.com/user/gui-and-headless-browsers/
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script: 
  #- g++ ucorridor.cpp -o corridor -lSDL -lSDL_ttf -lSDL_image
  - qmake
  - make
  - ./GameCorridor &
  - sleep 10
  # Code coverage
  - ./get_code_cov
  - codecov
  # OCLint
  - ./do_oclint

after_success:
  - bash <(curl -s https://codecov.io/bash)











